#!/bin/bash

# check if binary is already linked, if so remove it
titan_exists=/usr/local/bin/titan
if [ -f "$titan_exists" ]; then
    sudo rm -rf /usr/local/bin/titan /usr/local/lib/titan
fi

cargo build --release

sudo cp target/release/titan /usr/local/lib
sudo ln -s /usr/local/lib/titan /usr/local/bin/titan